name: Testing Matrix

on:
  workflow_dispatch:
  push:

jobs:
  run_all_tests:
    strategy:
      fail-fast: false
      matrix:
        xcode-version: [14.2, 15.2]
        destination: ['platform=iOS Simulator,OS=17.2', 'platform=macOS', 'platform=macOS,variant=Mac Catalyst']

    runs-on: macos-13

    steps:
      - uses: actions/checkout@v3

      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: ${{ matrix.xcode-version }}

      - name: Xcode Version
        run: xcodebuild -version

      - name: Show SDKs
        run: xcodebuild -showsdks

      - name: Show Destinations
        run: xcodebuild -scheme LiveKit -showdestinations

      - name: Run All Tests
        run: xcodebuild test -scheme LiveKit -destination '${{ matrix.destination }}'
