name: Testing Matrix

on:
  workflow_dispatch:
  push:

jobs:
  basic_test:
    strategy:
      matrix:
        platform: [iOS, macOS]
        xcode-version: [14.2, 15.2]

    runs-on: macOS-13-arm64

    steps:
      - uses: actions/checkout@v3

      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: ${{ matrix.xcode-version }}

      - name: Xcode Version
        run: xcodebuild -version

      - name: Show SDKs
        run: xcodebuild -showsdks

      - name: List Schemes
        run: xcodebuild -list

      - name: Execute Test
        run: xcodebuild -scheme LiveKitTests -destination 'platform=macOS,arch=arm64' -only-testing 'LiveKitTests/Basic' test

      # xcodebuild test -scheme LiveKit -sdk iphonesimulator17.2 -destination "OS=17.4,name=iPhone 13 Mini"
